name: main

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: make setup
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: make test
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: make lint
